redis:
  host: 0.0.0.0
  port: 6379
  netty-threads: 32
  threads: 16
  auth:
    enabled: true
    password: 'password123'
hub-servers:
  - 'hub'
servers:
  hubs:
    - 'hub'
  queued-servers:
    factions:
      name: 'factions'
      interval: 5000