servers:
  hub-servers:
    - 'hub'
  queued-servers:
    factions:
      name: 'factions'
      interval: 5000
position-message-update-interval: 10000
blacklisted-kick-messages:
  - 'whitelisted'

restart-message:
  - 'restart'