package com.massivecraft.factions.zcore.factionboosters;

public enum BoosterType {

    DAMAGE_INCREASE_IN_ENEMY_TERRITORY,
    DAMAGE_INCREASE_IN_MEMBER_TERRITORY,
    DAMAGE_REDUCTION_IN_ENEMY_TERRITORY,
    DAMAGE_REDUCTION_IN_MEMBER_TERRITORY,
    SLOWNESS_POTION_EFFECT_TRAP,
    WEAKNESS_POTION_EFFECT_TRAP,

}
