#Directions - (VERTICAL_UP,VERTICAL_DOWN,HORIZONTAL)
#ItemFlags - (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html)
#Enchantments - (http://docs.codelanx.com/Bukkit/1.8/org/bukkit/enchantments/Enchantment.html)
#Material - (http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Material.html)
#DyeColor (Colors used for glass panes, wool, and glass) - (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/DyeColor.html)
interval: 6
enable-combattagplus-integration: true
#May cause issues with minecraft clients, this is not fixable without causing mas amount of ItemStack instantiations.
disable-lava-bucket-player-use: true
menu:
  options:
    close-inventory-on-purchase: false
    close-inventory-on-no-money: false
  name: '                 &e&l(*) &fGens &e&l(*)'
  size: 18
  fill:
    enabled: true
    glass-pane-color: 'BLACK'
    enchanted: true
  items:
    0: 'cobblestone-up'
    9: 'obsidian-up'
    2: 'cobblestone-horizontal'
    11: 'obsidian-horizontal'
gens:
  cobblestone-up:
    length: 256
    patch: false
    price: 10
    direction: 'VERTICAL_UP'
    material: 'COBBLESTONE'
    menu:
      amount: 1
      material: 'COBBLESTONE'
      name: '&d&l(!) &fCobblestone GenBucket &d&l(!)'
      lore:
        - ''
        - ' &dDirection: &fUP'
        - ' &dPrice: &f$10'
        - ''
      enchants:
        - 'DURABILITY:1'
      itemflags:
        - 'HIDE_ENCHANTS'
    item:
      amount: 1
      material: 'COBBLESTONE'
      name: '&d&l(!) &fCobblestone GenBucket &d&l(!)'
      lore:
        - ''
        - ' &dDirection: &fUP'
        - ' &dPlace this genbucket to generate cobblestone '
        - ''
      enchants:
        - 'DURABILITY:1'
      itemflags:
        - 'HIDE_ENCHANTS'
  obsidian-up:
    length: 256
    patch: false
    price: 5000
    direction: 'VERTICAL_UP'
    material: 'OBSIDIAN'
    menu:
      amount: 1
      material: 'OBSIDIAN'
      name: '&d&l(!) &fObsidian GenBucket &d&l(!)'
      lore:
        - ''
        - ' &dDirection: &fUP'
        - ' &dPrice: &f$5000'
        - ''
      enchants:
        - 'DURABILITY:1'
      itemflags:
        - 'HIDE_ENCHANTS'
    item:
      amount: 1
      material: 'OBSIDIAN'
      name: '&d&l(!) &fObsidian GenBucket &d&l(!)'
      lore:
        - ''
        - ' &dDirection: &fUP'
        - ' &dPlace this genbucket to generate obsidian '
        - ''
      enchants:
        - 'DURABILITY:1'
      itemflags:
        - 'HIDE_ENCHANTS'
  cobblestone-horizontal:
    length: 96
    patch: false
    price: 250
    direction: 'HORIZONTAL'
    material: 'COBBLESTONE'
    menu:
      amount: 1
      material: 'COBBLESTONE'
      name: '&d&l(!) &fCobblestone GenBucket &d&l(!)'
      lore:
        - ''
        - ' &dDirection: &fHorizontal'
        - ' &dPrice: &f$250'
        - ''
      enchants:
        - 'DURABILITY:1'
      itemflags:
        - 'HIDE_ENCHANTS'
    item:
      amount: 1
      material: 'COBBLESTONE'
      name: '&d&l(!) &fCobblestone GenBucket &d&l(!)'
      lore:
        - ''
        - ' &dDirection: &fHorizontal'
        - ' &dPlace this genbucket to generate cobblestone '
        - ''
      enchants:
        - 'DURABILITY:1'
      itemflags:
        - 'HIDE_ENCHANTS'
  obsidian-horizontal:
    length: 96
    patch: false
    price: 2500
    direction: 'HORIZONTAL'
    material: 'OBSIDIAN'
    menu:
      amount: 1
      material: 'OBSIDIAN'
      name: '&d&l(!) &fObsidian GenBucket &d&l(!)'
      lore:
        - ''
        - ' &dDirection: &fHorizontal'
        - ' &dPrice: &f$2500'
        - ''
      enchants:
        - 'DURABILITY:1'
      itemflags:
        - 'HIDE_ENCHANTS'
    item:
      amount: 1
      material: 'OBSIDIAN'
      name: '&d&l(!) &fObsidian GenBucket &d&l(!)'
      lore:
        - ''
        - ' &dDirection: &fHorizontal'
        - ' &dPlace this genbucket to generate cobblestone '
        - ''
      enchants:
        - 'DURABILITY:1'
      itemflags:
        - 'HIDE_ENCHANTS'